### ISSUE TITLE
any idea on how to add the push and pop instruction simulation

### ISSUE THREAD

**Issue by asmwarrior** [mucan54/8051-python-simulator#1]
I would like to use this simulator for teaching.

I can generate many asm files (which contains some random numbers) in the asm instructions.
Then I can send those files to my students, and the students can verify the code, and give the results.

I can check whether their answer is correct or not by this simulator.

So, any idea to implement the pop and push command? which need to implement a special sfr `SP`.

Thanks.

**Comment by mucan54** [comment]
Can you send me a documentation to how it should work, then I can implement soon.

**Comment by kimstik** [comment]
https://www.keil.com/support/man/docs/is51/is51_push.htm
should help you

**Comment by asmwarrior** [comment]
Yes, @kimstik  gives the correct document. Thanks.

**Comment by kimstik** [comment]
One more reference example is "cl_51core::instruction_c0" in
https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/sim/ucsim/s51.src/mov.cc

**Comment by asmwarrior** [comment]
I implement this feature, see here:

[add support for the push and pop instruction and many other improvement by asmwarrior · Pull Request #4 · mucan54/8051-simulator](https://github.com/mucan54/8051-simulator/pull/4)

**Comment by mucan54** [comment]
Thank you.
