### ISSUE TITLE
what does the variable name memd mean in your code

### ISSUE THREAD

**Issue by asmwarrior** [mucan54/8051-python-simulator#2]
Hi, when debugging the code. 
I'm not fully understand the logic.

Some of the variable names are not clear to me.

For example, `mem` is the initial memory set.
and what does `memd` mean? the char `d` means it is destination? or data?

There is a function named `mov_v`, what does the `v` mean?

Thanks.

**Comment by asmwarrior** [comment]
If I have a function like:

~~~~
work([['P1',3], ['P2', 4]], 'test.asm', 5)    
~~~~

Then, I see the `mem2` is the `[['P1',3], ['P2', 4]]`.

While in each loop, I see one statement:

~~~~
        memd=[]              # memd reset here!
        item=content[x]      # content holds all the instructions, we fetch only one instruction
        
        memd=[a[0] for a in mem]
        if(item.find('MOV')!=-1 and item.find('MOVC')==-1):
            ...
            ...
~~~~

I see that `memd` get reset in everytime we fetch a new instruction, but what it does is:
~~~~
memd=[a[0] for a in mem]
~~~~

Only the first pair get copied to the `memd`?

I mean if I have those two values:
~~~~
IPdb [2]: mem
[[['P1', 3], ['P2', 4]]]

IPdb [3]: memd
[['P1', 3]]
~~~~

Only the first element get copied to `memd`?

Thanks.

**Comment by mucan54** [comment]
Hi,
Let me explain what will program do when you run this : work([['P1',3], ['P2', 4]], 'test.asm', 5)    

- [['P1',3], ['P2', 4]] this one means that first state of ports so your processor P1 port set to 3, and P2 is set to 4, before the program runs.

- test.asm is your code to run

- 5 is cycle number, it depends on your codes functionality, sometimes it should be much higher, you can find best for you via trying.

mov_v returns value of register, mov_d assigns value to register.

memd is like map of mem, when you want to assign a value to a register first find its index in memd, then assign it at mem.

```
def mov_d(s1, s2, memd):
    if(s1 in memd):
       va=memd.index(s1)
       mem[va]=[mem[va][0],s2]
    else:
       mem.append([s1,s2])
```

**Comment by asmwarrior** [comment]
Hi, thanks for the explanation.

I have create a pull request:

[add support for the push and pop instruction and many other improvement by asmwarrior · Pull Request #4 · mucan54/8051-simulator](https://github.com/mucan54/8051-simulator/pull/4)

I have add some comments and other improvement.
