### ISSUE TITLE
testbench

### ISSUE THREAD

**Issue by kimstik** [mucan54/8051-python-simulator#5]
May I suggest some test code for you to make your project robust?

Please have a look to following 2 files:
https://opencores.org/websvn/filedetails?repname=8051&path=%2F8051%2Ftrunk%2Fasm%2Ftestall.asm
https://opencores.org/websvn/filedetails?repname=light52&path=%2Flight52%2Ftrunk%2Ftest%2Fcpu_test%2Fsrc%2Ftb51_cpu.a51

**Comment by asmwarrior** [comment]
I think the code has many bugs, so it is not ready to run a test bench.
