### ISSUE TITLE
question about handling DB statement

### ISSUE THREAD

**Issue by asmwarrior** [mucan54/8051-python-simulator#6]
What does the hard-coded 10 here in this code:

~~~~
        if(item.find('DB')!=-1):
            mov_d(item[0:item.find(':')],getv(item[10:len(content[0])]),memd)
~~~~

When handling the `DB` statement, I'm not sure what dose `10` used for?

**Comment by asmwarrior** [comment]
For this statement
~~~~
MOVC A,     @A+DPTR
~~~~
to run correctly, I have to prepare such predefined memd

~~~~
work([['A', 4], ['DPTR', 'TAB'], ['TAB', [2,3,4,5,6,7]]], 'test2.asm', 20)
~~~~

So, the function 

~~~~
getv(item[10:len(content[0])])
~~~~

looks like to parse some statement like:

~~~~
TAB: DB 2,3,4,5,6,7
~~~~

But the code snippet:

~~~~
        if(item.find('DB')!=-1):
            mov_d(item[0:item.find(':')],getv(item[10:len(content[0])]),memd)
~~~~

looks wrong here.

**Comment by asmwarrior** [comment]
I implement this feature in my master branch in

https://github.com/asmwarrior/8051-simulator

**Comment by mucan54** [comment]
merged thanks
